In [1]:
import pandas as pd


file_path = r'C:\Users\SK\Downloads\Iris'


try:
    df = pd.read_csv(file_path)
except Exception:
    df = pd.read_csv(file_path + '.csv')

print("Dataset successfully loaded!")
print(f"Shape of Dataset: {df.shape}")
df.head()

Dataset successfully loaded!
Shape of Dataset: (150, 6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
print("=== 5 loc[] Examples (Label-based) ===")

# 1. Single row by label
print("\n1. Row at label 0:")
display(df.loc[0])

# 2. Slice of rows and specific columns by name
print("\n2. Rows 0 to 4 with specific columns:")
display(df.loc[0:4, ['SepalLengthCm', 'SepalWidthCm', 'Species']])

# 3. Column slice from SepalLengthCm to PetalWidthCm
print("\n3. Column slice (SepalLengthCm to PetalWidthCm):")
display(df.loc[0:2, 'SepalLengthCm':'PetalWidthCm'])

# 4. Conditional filtering with loc
print("\n4. Filter rows where Species is 'Iris-setosa':")
display(df.loc[df['Species'] == 'Iris-setosa', ['Id', 'Species', 'PetalLengthCm']].head(3))

# 5. Specific non-consecutive rows and columns
print("\n5. Specific rows [2, 5, 10] and columns:")
display(df.loc[[2, 5, 10], ['Id', 'SepalLengthCm']])

=== 5 loc[] Examples (Label-based) ===

1. Row at label 0:

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

2. Rows 0 to 4 with specific columns:

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa
3            4.6           3.1  Iris-setosa
4            5.0           3.6  Iris-setosa

3. Column slice (SepalLengthCm to PetalWidthCm):

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2

4. Filter rows where Species is 'Iris-setosa':

   Id      Species  PetalLengthCm
0   1  Iris-setosa            1.4
1   2  Iris-setosa            1.4
2   3  Iris-setosa            1.3

5. Specific rows [2, 5, 10] and columns:

    Id  SepalLengthCm
2    3            4.7
5    6            5.4
10  11            5.4

In [5]:
print("=== 5 iloc[] Examples (Position-based) ===")

# 1. Single row by integer index
print("\n1. Row at position 0:")
display(df.iloc[0])

# 2. Positional slicing for rows and columns
print("\n2. Rows 0-4 and columns 0-2:")
display(df.iloc[0:5, 0:3])

# 3. Specific row indices and column indices
print("\n3. Specific rows [1, 3, 5] and columns [1, 4]:")
display(df.iloc[[1, 3, 5], [1, 4]])

# 4. Negative indexing for the last column
print("\n4. Last column (Species) for first 5 rows:")
display(df.iloc[0:5, -1])

# 5. Step size slicing (every 30th row)
print("\n5. Every 30th row using step size:")
display(df.iloc[0:150:30, 0:4])

=== 5 iloc[] Examples (Position-based) ===

1. Row at position 0:

Id                         1
SepalLengthCm            5.1
SepalWidthCm             3.5
PetalLengthCm            1.4
PetalWidthCm             0.2
Species          Iris-setosa
Name: 0, dtype: object

2. Rows 0-4 and columns 0-2:

   Id  SepalLengthCm  SepalWidthCm
0   1            5.1           3.5
1   2            4.9           3.0
2   3            4.7           3.2
3   4            4.6           3.1
4   5            5.0           3.6

3. Specific rows [1, 3, 5] and columns [1, 4]:

   SepalLengthCm  PetalWidthCm
1            4.9           0.2
3            4.6           0.2
5            5.4           0.4

4. Last column (Species) for first 5 rows:

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

5. Every 30th row using step size:

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0      1            5.1           3.5            1.4
30    31            4.8           3.1            1.6
60    61            5.0           2.0            3.5
90    91            5.5           2.6            4.4
120  121            6.9           3.2            5.7

In [7]:
comparison_data = {
    "Feature": ["Selection Basis", "Boundary Inclusion", "Column Reference", "Handling Data Changes"],
    "loc[]": ["Uses labels (index names or column names)", "Both start and end labels are inclusive", "Requires exact column name strings", "Safe against column reordering/insertion"],
    "iloc[]": ["Uses integer positions (0-indexed)", "End index is exclusive (like Python slicing)", "Requires integer column indices", "Breaks if column positions change"]
}

df_comparison = pd.DataFrame(comparison_data)
display(df_comparison)

,Feature,loc[],iloc[]
0,Selection Basis,Uses labels (index names or column names),Uses integer positions (0-indexed)
1,Boundary Inclusion,Both start and end labels are inclusive,End index is exclusive (like Python slicing)
2,Column Reference,Requires exact column name strings,Requires integer column indices
3,Handling Data Changes,Safe against column reordering/insertion,Breaks if column positions change